### ISSUE TITLE
Example with a nix missing ocaml package does not seem right

### ISSUE THREAD

**Issue by frisoft** [emilpriver/go-hugo-portfolio#9]
Hi @emilpriver . 
With this commit, https://github.com/emilpriver/go-hugo-portfolio/commit/81ab1c745040218e910ee220fc4829dbc91b2bda, you removed the example with builtins.fetchurl.
Is it what you intended? The example does not seem right now.

**Comment by emilpriver** [comment]
Hey, Thank you. I removed it by accident. Thank you for letting me know

Have a good day! :D

**Comment by frisoft** [comment]
No problems, @emilpriver , I'm interested in learning OCaml and I'd love to use Nix (flake) for the setup of my exploration projects.

Your post will be very helpful.

Thank you

**Comment by emilpriver** [comment]
I am atm writing a article on going from devshell -> production where the example code is OCaml and nix, and I also have a ocaml-nix-template which I use in this article. Give it some days and it will be there :D

**Comment by frisoft** [comment]
That sounds great 👍 . Looking forward to reading your new article. :-)

**Comment by emilpriver** [comment]
Published it the other day, exists here https://priver.dev/blog/nix/from-computer-to-production-with-nix/
hope you like it :D

**Comment by frisoft** [comment]
Great article, @emilpriver. I liked that you covered almost every use of the flake.nix file, including testing as well.
I need to look into the flake-parts nix module, which I did not know about.

Is your flake template used by the Riot dev community?

Thank you again for the article; it was very interesting and useful.

**Comment by emilpriver** [comment]
> Great article, @emilpriver. I liked that you covered almost every use of the flake.nix file, including testing as well.
> I need to look into the flake-parts nix module, which I did not know about.
> 
> Is your flake template used by the Riot dev community?
> 
> Thank you again for the article; it was very interesting and useful.

Hey,
No, we have another flake in the riot repo

**Comment by frisoft** [comment]
I see. Thank you
